### ISSUE TITLE
untar failed

### ISSUE THREAD

**Issue by pgyogesh** [yugabyte/yb-log-analyzer-py#14]
**Describe the bug**

- Untar is failing.

**To Reproduce**
1. Go to lincoln
2. Change the directory to ~/yogesh/
3. Run command.

```
 python3 analyzer.py -d /cases/6847/universe-logs -p 10
```

5. See the error

```
2023-06-30 05:32:14,672:INFO:- Extracting file /cases/6847/universe-logs/yb-prod-ros-pm-kobe-1688031337.tar.gz
Traceback (most recent call last):
  File "/home/support/yogesh/yb-log-analyzer-py/analyzer.py", line 232, in <module>
    extractAllTarFiles(args.directory)
  File "/home/support/yogesh/yb-log-analyzer-py/analyzer.py", line 130, in extractAllTarFiles
    tar.extractall(os.path.dirname(file))
  File "/usr/lib/python3.10/tarfile.py", line 2059, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.10/tarfile.py", line 2100, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.10/tarfile.py", line 2173, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.10/tarfile.py", line 2222, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/usr/lib/python3.10/tarfile.py", line 248, in copyfileobj
    buf = src.read(bufsize)
  File "/usr/lib/python3.10/gzip.py", line 301, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.10/gzip.py", line 507, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by pgyogesh** [comment]
It failed even with the tar command.

```
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```
